version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: finance
      MYSQL_USER: financeuser
      MYSQL_PASSWORD: financepass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/finance?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: financeuser
      SPRING_DATASOURCE_PASSWORD: financepass
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: 